### ISSUE TITLE
Logging is sometimes re-entrant

### ISSUE THREAD

**Issue by LeonarddeR** [enthought/comtypes#192]
Within [NVDA](https://www.nvaccess.org/), we use comtypes to access com objects. Until now, we ignored logging messages coming from comtypes. When I started investigating piping comtypes logging to the NVDA log, I noticed that NVDA crashed in a few minutes after enabling debug logging.

[Here](https://github.com/nvaccess/nvda/files/3738369/reentrancy.txt) is an example traceback generated when comtypes logging is set to debug. It looks like some log messages generate another message that causes re-entrancy.

**Comment by junkmd** [comment]
@leonardder

Is this still a problem?

**Comment by vasily-v-ryabov** [comment]
From brief look it seems a threading issue. See this StackOverflow question: https://stackoverflow.com/q/45680378/3648361 From the first look I couldn't understand whether we can fix it in `comtypes` or not.

**Comment by leonardder** [comment]
It's a long time ago I investigated this. There have been some logging changes in NVDA related to comtypes, see https://github.com/nvaccess/nvda/pull/14317

**Comment by junkmd** [comment]
@leonardder 

I don't think this issue is limited to `comtypes`.

I think @vasily-v-ryabov is right, it is a problem that occurs with asynchronous, parallelprocessing or multiprocessing.
I think the solution is to eliminate logging from `comtypes` or to prevent your project's logging from picking up the library's logs.

I am not in favor of eliminating logging from `comtypes`.

Your project PR seems to have accomplished not picking up any logs on the library side.

What about this issue?

**Comment by junkmd** [comment]
I believe this is more of a `logging` issue than a `comtypes` issue, so I will close this.  

As with the approach taken in nvda, I think this is a topic that can be resolved by addressing it on the project side using this library.
