### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by PhilippSelenium** [enthought/comtypes#230]
The documentation linked in the readme https://pythonhosted.org/comtypes/  is for version 1.1.3 released in 2016.

**Comment by vasily-v-ryabov** [comment]
AFAIK there were no any changes in the docs since this date. @cfarrow @jaraco do you know something about access to these docs?

**Comment by cfarrow** [comment]
My recollection is that upload access for pythonhosted is derived from PyPI access privileges. You should have full access to that.

**Comment by vasily-v-ryabov** [comment]
Wow! This is interesting, but I couldn't find any instruction how to update the pythonhosted docs. PyPA recommends ReadTheDocs service (see https://packaging.python.org/tutorials/creating-documentation/) which I use for pywinauto.

**Comment by jaraco** [comment]
Right. Support for hosting docs on pythonhosted.org (PyPI) was removed years ago. I recommend to [destroy the docs](https://stackoverflow.com/a/41856147).

**Comment by vasily-v-ryabov** [comment]
@jaraco thanks! I will try to remove old docs when I have time to upload them to ReadTheDocs first.

**Comment by PhilippSelenium** [comment]
Ping

**Comment by junkmd** [comment]
As discussed in https://github.com/enthought/comtypes/pull/343, pythonhosted is no longer updateable. The documentation content is outdated. Many of the sample codes are from the Python2 era and do not work in Python3.

Let’s migrate somewhere and update the content.
I want to discuss with everyone what is beneficial for the community.

When I was looking for a good place to host, I found https://docs.enthought.com/.
It hosts the documentation for enthought's repositories such as https://github.com/enthought/mayavi (http://docs.enthought.com/mayavi/mayavi/) and https://docs.enthought.com/pyql/ (https://github.com/enthought/pyql).
Since the `comtypes` codebase is hosted by enthought, I think it would be reasonable to host the documentation at https://docs.enthought.com/comtypes/ if there is no policy issue.

The URL currently shows a 404 error from GitHub Pages. This means that if we can host it here, it might be easier to maintain and build than using a separate service like readthedocs, since the documentation and codebase hosting service would be the same GitHub.

- As a trial, on [a branch of my forked repository](https://github.com/junkmd/comtypes/tree/ghp_docs_demo), I set it up so that GitHub Pages could recognize the content made with the build script from the pythonhosted era.
But the [published content](https://junkmd.github.io/comtypes/) did not work well with css and other things.
It seems that some adjustments are needed.

Alternatively, we can consider using readthedocs.

As you can see, I'm not very familiar with sphinx and hosting services, so I need someone who knows more about them to help me.

@cfarrow
@jaraco
@vasily-v-ryabov

Do you have any opinions?

**Comment by jaraco** [comment]
No strong opinions. I've migrated my projects to use Read The Docs. See [jaraco/skeleton](/jaraco/skeleton) for how my projects are configured to build using RTD. If you'd like me to apply those settings to comtypes, I'd be happy to do so.

**Comment by junkmd** [comment]
@jaraco
Thank you for your proposal.

It's very reassuring to have a packaging expert and PyPA member like you involved in this issue.

@vasily-v-ryabov had agreed to the migration to ReadTheDocs in [the previous comment](https://github.com/enthought/comtypes/issues/230#issuecomment-832586358).

Also, I would like to confirm whether @cfarrow, a member of enthought, has any opinions on the migration to RTD.

If there are no problems or concerns, I would like you to apply the settings for RTD to `comtypes`.

**Comment by junkmd** [comment]
@cfarrow 
Do you have any thoughts on docs migration?

**Comment by cfarrow** [comment]
Sorry for the delayed response.

I think a service that is open to many projects, like ReadTheDocs, is the best option.

Hosting on the Enthought site would not be ideal for a multi-collaborator project like this.

**Comment by junkmd** [comment]
> I think a service that is open to many projects, like ReadTheDocs, is the best option.
> 
> Hosting on the Enthought site would not be ideal for a multi-collaborator project like this.

Thank you for your opinion. I understood!

**Comment by junkmd** [comment]
@jaraco 

I have confirmed that the main maintainers of this project have no objections to migrating the documentation to ReadTheDocs.

Feel free to apply the ReadTheDocs settings to this project.

**Comment by junkmd** [comment]
Through my recent contributions to CPython, I've gained a better understanding of modern Sphinx usage.

I added the necessary files for readthedocs to my forked repo, and successfully built and deployed them.

I’m planning to set up `comtypes.readthedocs.io` next.

I also plan to assign RTD privileges to the maintainers of this project.
Please share a link to your RTD profile page in this issue.

@jaraco 
@vasily-v-ryabov 
@cfarrow

**Comment by junkmd** [comment]
The following URL will serve as the host for the new documentation:
https://comtypes.readthedocs.io/en/latest/

The explanation about the client remains the same as in version 1.1.11, and the explanation about the server also remains the same as in version 0.5.

However, this move frees us from pythonhosted and allows us to make edits.

Let’s work with the community to gradually update the content.

**Comment by junkmd** [comment]
After migrating the documentation to https://comtypes.readthedocs.io/, the theme and style were also modernized. 

The links in the README are planned to be updated when releasing version 1.4.9.

**Comment by junkmd** [comment]
@dpinte 

I'd like to add you as a maintainer for `comtypes`' RTD.
This would prevent a situation where no one can maintain it in a pinch.

What do you think?

**Comment by dpinte** [comment]
@junkmd that works for me! I can't guarantee a very fast response time but I'm definitely going to be present in the long run.
