### ISSUE TITLE
getting Syntax Error : Invalid Syntax with python 3.10.10

### ISSUE THREAD

**Issue by dineshu07** [enthought/comtypes#517]
Hi

I'm trying to use pywinauto, following error comes right after the import statement. Please help me to resolve this. This is happening only on windows 10 machine. 

![Screenshot from 2024-02-22 17-59-15](https://github.com/enthought/comtypes/assets/13025236/a3604395-e9c3-47bf-82c1-7055bcebbd44)

**Comment by junkmd** [comment]
Hi,

This is likely due to a Python crash occurring during the `comtypes` process of writing code to the `.py` files in `.../comtypes/gen/...` (See also https://github.com/enthought/comtypes/issues/114).

I suggest running `py -m comtypes.clear_cache` (See also https://github.com/enthought/comtypes/pull/478 and [`CONTRIBUTING.md`](https://github.com/enthought/comtypes/blob/main/CONTRIBUTING.md#working-on-developments)). This command will delete those partial wrapper files.
Afterward, please call `pywinauto` again; it will regenerate the `.py` files.

Please let us know the results after trying the above steps.

**Comment by dineshu07** [comment]
Hi @junkmd It worked!. Thank you so much for your quick solution.
