### ISSUE TITLE
Anaconda Python + comtypes 1.1.2

### ISSUE THREAD

**Issue by alexanderschuetz** [enthought/comtypes#93]
I had to switch from Active Python to Anaconda Python (2.7.10) under Windows 7 64bit. I installed the latest comtypes 1.1.2 and still get an error. But the code worked with Active Python well.

``` python
from ctypes import *
import comtypes.client
from comtypes.automation import *

print "test"
```

It throws the following error:

``` python
test
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import comtypes.client
  File "C:\Program Files\Anaconda\lib\site-packages\comtypes-1.1.2-py2.7.egg\com
types\__init__.py", line 902
    class _compointer_base(c_void_p, metaclass=_compointer_meta):
                                              ^
SyntaxError: invalid syntax
```

Is this because of an incompability between Anaconda and comtypes?

**Comment by vasily-v-ryabov** [comment]
I think I had the same issue and found a workaround.
It looks like you've installed comtypes on Active Python 3.x first and then trying to install it on 2.x Anaconda from the same local folder. `comtypes` uses `2to3` on-the-fly fixes while installing on 3.x So these changes are not get back.

Just try to unpack comtypes to another clean folder and try install on Anaconda 2.x by `python setup.py install`. Hope it helps.

**Comment by junkmd** [comment]
Since metaclasses are not currently used in this manner, there should be no problem.

https://github.com/enthought/comtypes/blob/0f3cf2b6d309d887eed92dd2b6d4393883ccbc69/comtypes/__init__.py#L15-L50

https://github.com/enthought/comtypes/blob/0f3cf2b6d309d887eed92dd2b6d4393883ccbc69/comtypes/__init__.py#L599-L600

@alexanderschuetz
if the issue remains, please re-open.
